### ISSUE TITLE
Issue while submitting the build to App Store

### ISSUE THREAD

**Issue by boominadhaprakash** [MSG91/sendotp-ios#1]
I have implemented this framework in my project. But I am getting issue while submitting the build to App Store. My App deployed target version is 9.0. Please provide me the solution.

<img width="744" alt="appstore_issue" src="https://user-images.githubusercontent.com/16302912/36029521-86c4b6f6-0dc9-11e8-894a-b22c0be7805a.png">

**Comment by hussain3152** [comment]
This is fixed now

**Comment by saurabh-dk** [comment]
Hi, this issue is still not fixed. I am getting exact same error and I am using latest framework I downloaded on 28th December 2018. I can neither publish my app on App Store nor put it on Test Flight for testing with client. Please fix this. Thank you.

**Comment by boominadhaprakash** [comment]
@saurabhDuzumaki Don't wait for their fixes. You can try to call their API webservices manually without using this Framework. I have done like that and submitted the app to appstore. I am just giving you the idea.

**Comment by hussain3152** [comment]
@saurabhDuzumaki  please provide the errors that you are facing, It would be great if you share the screenshots of error that you are facing currently.

**Comment by saurabh-dk** [comment]
> @saurabhDuzumaki please provide the errors that you are facing, It would be great if you share the screenshots of error that you are facing currently.

As I contacted your support, I tried integrating the library again.
Steps I followed =>

- Cloned this project
- Copied and pasted SendOTPFramework.framework file from sendotp-ios-master project to my project's Framework folder.
- Went to General -> Embedded Libraries -> added (+) the above pasted framework in it which then automatically appeared in "Linked Frameworks and Libraries".
- Followed everything mentioned in the github README
- As you can see, everything worked fine if I compiled and ran it directly by connecting it to physical device 
![screenshot 2019-01-28 at 11 45 14 am](https://user-images.githubusercontent.com/22277943/51820922-48811480-22fd-11e9-8fd5-1014da28f6f7.png)
- But when I tried to archive it, it fails with following error.
![screenshot 2019-01-28 at 12 25 20 pm](https://user-images.githubusercontent.com/22277943/51820968-6f3f4b00-22fd-11e9-8db9-f1ace6630b98.png)
- To solve this, I set Enable Bitcode to No
- It then successfully gets Archived.
- But when I try to upload the archive to App Store, it fails with following errors.
![screenshot 2019-01-28 at 2 20 09 pm](https://user-images.githubusercontent.com/22277943/51824513-7750b800-2308-11e9-8585-5c3d213c4c1e.png)

Please fix this or guide me to fix it. Otherwise I would have no option other than calling API webservices as @boominadhaprakash suggested.

Thanks.

**Comment by sejalthesiya** [comment]
@saurabhDuzumaki have you got any solution?

**Comment by saurabh-dk** [comment]
> @saurabhDuzumaki have you got any solution?

@sejalthesiya I had to use their web API services. Removed the library completely and called each endpoint individually.

**Comment by sejalthesiya** [comment]
Thanks for your feedback I will make change according to your solution.
